#!/usr/bin/env bash

# This script is based on the template here:
#
#     https://gist.github.com/pcrockett/8e04641f8473081c3a93de744873f787
#
# Useful links when writing a script:
#
# Shellcheck: https://github.com/koalaman/shellcheck
# vscode-shellcheck: https://github.com/timonwong/vscode-shellcheck
# https://blog.yossarian.net/2020/01/23/Anybody-can-write-good-bash-with-a-little-effort
#

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# TODO: Better run arguments in profile script; allow arguments, look at more than just $1

[[ "${BASH_VERSINFO[0]}" -lt 4 ]] && echo "Bash >= 4 required" && exit 1

PROFILE_NAME="$1"

SANDBOX_ROOT=~/sandboxes
if [ -d "$SANDBOX_ROOT" ]; then
    rm -rf "${SANDBOX_ROOT:?}/$PROFILE_NAME" || true
fi

FJ_CONFIG=~/.config/firejail
if [ -d "$FJ_CONFIG" ]; then
    rm "$FJ_CONFIG/$PROFILE_NAME.profile" || true
fi

BIN_DIR=~/.local/bin
if [ -d "$BIN_DIR" ]; then
    rm "$BIN_DIR/start-$PROFILE_NAME" || true
fi

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
HOOK_DIR="$SCRIPT_DIR/hooks"
if [ -f "$HOOK_DIR/post-destroy.sh" ]; then
    "$HOOK_DIR/post-destroy.sh" "$PROFILE_NAME"
fi
